name = "musicai-cdn-worker"
compatibility_date = "2025-12-11"
account_id = "6a94a1258e8b853bae5b2ecbe5dfd64a"

# Bind the R2 bucket created in your Cloudflare account
[[r2_buckets]]
binding = "R2_MEDIA"
bucket_name = "tingomusiclibrary"
preview_bucket_name = "tingomusiclibrary"

# Add any other worker settings here. Replace account_id before publishing.
